defaults:
  - agent: sac
  - env: dmc
  - _self_

seed: 1
device: 'cuda'
total_steps: 10000

wandb_cfg:
  use_wandb_log: True
  entity: 'grandpadzb'

Trainer:
  _target_: train.Trainer

  agent: ???
  env: ???
  env_eval: ???

  exploration_steps: 2000
  eval_interval: 10000
  log_interval: 5000
  save_interval: 100000
  target_update_interval: 1
  gradient_step_interval: 1
  n_gradient_steps: 1


